name: 🌕 CMake Build Matrix
env:
  aversion: 3.8.8

on: [push]

jobs:
  mybuild:
    name: ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {
              os: windows-latest,
              bin: 'src/Release/main_run.exe',
              cmakeConfig: '-A Win32 -T v142,host=x64',
              cmakeBuildConfig: '--config Release',
              prescript: 'chcp 65001',
              sudo: '  ',
            }
          # - {
          #     os: ubuntu-latest,
          #     bin: './src/main_run',
          #     prescript: 'cat /proc/cpuinfo; export CXX=clang++',
          #     cmakeConfig: ' -D NODOOR32=1 ',
          #     cmakeBuildConfig: '',
          #     sudo: ' sudo ',
          #   }

          # - {
          #     os: macos-latest,
          #     bin: "./src/main_run",
          #     cmakeConfig: '',
          #     cmakeBuildConfig: '',
          #     sudo: ' ',
          #     prescript: "",
          #   }

    steps:
      - uses: actions/checkout@v2

      - name: run Builde with Node.js v14
        shell: bash
        run: |
            bash ./build.sh v14 ${{ aversion }} --using_github_actions
            ls -al

      - name: BUILDING Python on Windows - run get_externals.bat 
        if: matrix.config.os == 'windows-latest'
        run: |
            Python-3.8.8/PCbuild/get_externals.bat
            Python-3.8.8/PCbuild/build.bat -p x64

            dir Python-3.8.8/PCbuild/amd64
            dir Python-3.8.8/Include

      - name: run Builde with Node.js v15
        shell: bash
        run: |
            bash ./build.sh v15 3.8.8 --using_github_actions


#      - name: Copy artifact
#        shell: bash
#        run: |
#          cd build;
#          mkdir -p deb/${{ matrix.config.os }};
#          cp ${{ matrix.config.bin }} deb/${{ matrix.config.os }}
#
#
#      - uses: actions/upload-artifact@v2
#        with:
#          name: python-lucene_${{ github.sha }}_amd64
#          path: build/deb
#
